Remove error function
Signed-off-by: Tyler Levine <tyler@bitgo.com>

diff --git a/pr b/pr
--- a/pr
+++ b/pr
@@ -131,51 +131,6 @@ usage() {
 	esac
 }
 
-error() {
-	reason="${1:-}"
-	code=1
-	case $reason in
-		"sync" ) read -r -d '!!' template <<-EOF
-			Sync failed.
-			%s
-		!!
-		EOF
-		code=40
-		;;
-
-		"aborted" )
-		read -r -d '!!' template <<-EOF
-			Aborted: %s
-		!!
-		EOF
-		code=50
-		;;
-
-		"branch" )
-		read -r -d '!!' template <<-EOF
-			Error: cannot create pull request for local branch %s
-			%s
-		!!
-		EOF
-		code=50
-		;;
-
-		* ) read -r -d '!!' template <<-EOF
-			Unknown error. Good luck!
-			%s
-		!!
-		EOF
-		code=100
-		;;
-
-	esac
-
-	# shellcheck disable=SC2059
-	printf "${template}\\n" "${@:2}" >&2
-
-	exit $code
-}
-
 mark_pr_accepted() {
 	COMMIT="$1"
 	URL="$2"
@@ -215,16 +170,27 @@ cmd_accept() {
 	[ "$#" != 1 ] && usage accept && exit 1
 
 	pr=${1}
-	if [[ "$pr" =~ ^[0-9]+$ ]]; then
-		error "invalid pull request number: $pr"
+	if [[ ! "$pr" =~ ^[0-9]+$ ]]; then
+		echo "invalid pull request number: $pr"
+		exit 1
 	fi
 
-	PR_INFO="$(hub pr list -f '%H %U' -s open -L 1)"
+	echo -n "Checking out pull request $pr..."
+	RESULT=
+	if r="$(hub pr checkout "$pr")"; then
+		echo "OK"
+	else
+		echo "Error: checkout failed"
+		echo "$r"
+		exit 1
+	fi
+
+	PR_INFO="$(hub pr list -h "$(git rev-parse --abbrev-ref HEAD)" -f '%H %U' -s open -L 1)"
 	BRANCH="$(cut -d' ' -f1 <<< "$PR_INFO")"
 	COMMIT="$(git rev-parse "$BRANCH")"
 	URL="$(cut -d' ' -f2 <<< "$PR_INFO")"
 	echo -n "Fetching pull request $pr head branch $BRANCH..."
-	git fetch "origin/$BRANCH" > /dev/null 2>&1
+	git fetch origin "$BRANCH" > /dev/null 2>&1
 	echo "OK"
 
 	echo -n "Creating review tag..."
@@ -250,16 +216,17 @@ cmd_show() {
 
 	COMMIT="$(git rev-parse HEAD)"
 	FORMAT_SCRIPT="%(if:notequals=<$(git config user.email)>)%(taggeremail)%(then)%(taggeremail): Valid Review Tag%(end)"
-	valid_signed_tags=$(git for-each-ref \
+
+	valid_signed_tags="$(git for-each-ref \
 		--points-at "$COMMIT" \
 		--format "$FORMAT_SCRIPT" \
-		refs/tags/reviews | grep -c v \
-	)
-	if [ "$raw" -ne 1 ]; then
-		printf "Review tags for commit %s\\n" "$COMMIT"
+		refs/tags/reviews \
+	)"
+	if ! valid_count="$(grep -c "Valid Review Tag" <<< "$valid_signed_tags")"; then
+		valid_count=0
 	fi
-
-	echo "$valid_signed_tags"
+	[[ "$raw" != 1 ]] && printf "$valid_count valid review tag(s) for commit %s\\n" "$COMMIT"
+	[[ -n "$valid_signed_tags" ]] && echo "$valid_signed_tags"
 }
 
 update_pr() {
@@ -283,7 +250,8 @@ update_pr() {
 		echo "Updating pull request #$PR_NUMBER... "
 		git push origin "$(git rev-parse --abbrev-ref HEAD)"
 	else
-		error "Aborted: Pull request not updated"
+		echo "Aborted: Pull request not updated"
+		exit 1
 	fi
 }
 
@@ -332,7 +300,7 @@ cmd_sync() {
 	[ "$#" -eq 0 ] || { usage sync; exit 1; }
 
 	BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
-	[ "$BRANCH_NAME" == "$UPSTREAM" ] && error "branch" "$BRANCH_NAME" "Cannot create pull request with commits made directly on local upstream branch $UPSTREAM"
+	[ "$BRANCH_NAME" == "$UPSTREAM" ] && echo "Error: Cannot create pull request with commits made directly on local copy of upstream branch $UPSTREAM" && exit 1
 	PR_NUMBER="$(hub pr list -h "$BRANCH_NAME" -s open -f '%I' -L 1 2> /dev/null || echo -n 0)"
 
 	# check for existing open pr for this branch
@@ -347,7 +315,8 @@ cmd_sync() {
 	if [[ "$should_create" =~ ^[Yy]$ || "$should_create" == '' ]]; then
 		create_pr "$BRANCH_NAME"
 	else
-		error "aborted" "pull request not created"
+		echo "Aborted: pull request not created"
+		exit 0
 	fi
 }
 
@@ -372,7 +341,8 @@ cmd_merge() {
 	PR_NUMBER="$(hub pr list -h "$BRANCH_NAME" -s open -f '%I' -L 1)"
 
 	if [[ "$PR_NUMBER" == "" ]]; then
-		error "Failed to find open pull request for branch $BRANCH_NAME"
+		echo "Failed to find open pull request for branch $BRANCH_NAME"
+		exit 1
 	fi
 
 	cmd_verify > /dev/null 2>&1
@@ -396,6 +366,8 @@ cmd_verify() {
 	[ "$#" -gt 0 ] && usage verify && exit 1
 	# make sure tip of merged branch has at least the minimum number of signed review tags
 	local valid_signed_tags=0
+	BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
+	PR_NUMBER="$(hub pr list -h "$BRANCH_NAME" -s open -f '%I' -L 1)"
 	FORMAT_SCRIPT="%(if:notequals=<$(git config user.email)>)%(taggeremail)%(then)v%(end)"
 	valid_signed_tags=$(git for-each-ref \
 		--points-at "$BRANCH_NAME" \
